const mockData = {
    instruments: [
        {
            id: 1,
            code: 'HPLC-001',
            name: 'HPLC System 1',
            type: 'High Performance Liquid Chromatography (HPLC)',
            manufacturer: 'Agilent Technologies',
            modelNumber: '1260 Infinity II',
            serialNumber: 'SN-HPLC-2023-001',
            location: 'QC Lab - Room 101',
            status: 'operational',
            purchaseDate: '2023-01-15',
            warrantyExpiry: '2026-01-15',
            lastCalibration: '2024-11-01',
            nextCalibration: '2025-02-01',
            calibrationFrequency: 90,
            usageHours: 2450,
            testTypes: 'Potency testing, Impurity testing, Content uniformity',
            operators: 'Sarah Johnson, Emily Davis',
            notes: 'Primary HPLC system for routine analysis. UV detector at 254nm.',
            scheduledMaintenance: [
                {
                    start: '2025-02-01T08:00',
                    end: '2025-02-01T17:00',
                    type: 'Calibration',
                    technician: 'Robert Wilson',
                    notes: 'Quarterly calibration and performance verification'
                }
            ]
        },
        {
            id: 2,
            code: 'HPLC-002',
            name: 'HPLC System 2',
            type: 'High Performance Liquid Chromatography (HPLC)',
            manufacturer: 'Waters Corporation',
            modelNumber: 'Alliance e2695',
            serialNumber: 'SN-HPLC-2023-002',
            location: 'QC Lab - Room 102',
            status: 'operational',
            purchaseDate: '2023-03-20',
            warrantyExpiry: '2026-03-20',
            lastCalibration: '2024-10-15',
            nextCalibration: '2025-01-15',
            calibrationFrequency: 90,
            usageHours: 1890,
            testTypes: 'Dissolution testing, Stability testing',
            operators: 'Sarah Johnson, Lisa Anderson',
            notes: 'Secondary HPLC system with photodiode array detector.',
            scheduledMaintenance: []
        },
        {
            id: 3,
            code: 'GC-001',
            name: 'Gas Chromatograph 1',
            type: 'Gas Chromatography (GC)',
            manufacturer: 'Shimadzu',
            modelNumber: 'GC-2030',
            serialNumber: 'SN-GC-2023-001',
            location: 'QC Lab - Room 103',
            status: 'calibration',
            purchaseDate: '2023-02-10',
            warrantyExpiry: '2026-02-10',
            lastCalibration: '2024-12-01',
            nextCalibration: '2025-03-01',
            calibrationFrequency: 90,
            usageHours: 1650,
            testTypes: 'Residual solvents, Impurity testing',
            operators: 'Emily Davis, Lisa Anderson',
            notes: 'FID and TCD detectors. Currently under calibration.',
            scheduledMaintenance: [
                {
                    start: '2024-12-10T09:00',
                    end: '2024-12-10T16:00',
                    type: 'Calibration',
                    technician: 'Robert Wilson',
                    notes: 'Annual calibration in progress'
                }
            ]
        },
        {
            id: 4,
            code: 'KF-001',
            name: 'Karl Fischer Titrator',
            type: 'Karl Fischer Titration',
            manufacturer: 'Metrohm',
            modelNumber: '899 Coulometer',
            serialNumber: 'SN-KF-2023-001',
            location: 'QC Lab - Room 101',
            status: 'operational',
            purchaseDate: '2023-04-05',
            warrantyExpiry: '2026-04-05',
            lastCalibration: '2024-11-20',
            nextCalibration: '2025-02-20',
            calibrationFrequency: 90,
            usageHours: 980,
            testTypes: 'Moisture content',
            operators: 'Emily Davis, John Smith',
            notes: 'Volumetric KF titrator for moisture determination.',
            scheduledMaintenance: []
        },
        {
            id: 5,
            code: 'UV-001',
            name: 'UV-Vis Spectrophotometer 1',
            type: 'UV-Visible Spectrophotometry',
            manufacturer: 'PerkinElmer',
            modelNumber: 'Lambda 365',
            serialNumber: 'SN-UV-2023-001',
            location: 'QC Lab - Room 102',
            status: 'operational',
            purchaseDate: '2023-01-25',
            warrantyExpiry: '2026-01-25',
            lastCalibration: '2024-10-30',
            nextCalibration: '2025-01-30',
            calibrationFrequency: 90,
            usageHours: 2100,
            testTypes: 'Potency testing, Content uniformity',
            operators: 'Sarah Johnson, Lisa Anderson',
            notes: 'Double beam spectrophotometer with wavelength range 190-900nm.',
            scheduledMaintenance: []
        },
        {
            id: 6,
            code: 'UV-002',
            name: 'UV-Vis Spectrophotometer 2',
            type: 'UV-Visible Spectrophotometry',
            manufacturer: 'Thermo Scientific',
            modelNumber: 'Evolution 220',
            serialNumber: 'SN-UV-2023-002',
            location: 'QC Lab - Room 103',
            status: 'maintenance',
            purchaseDate: '2023-05-12',
            warrantyExpiry: '2026-05-12',
            lastCalibration: '2024-09-15',
            nextCalibration: '2024-12-15',
            calibrationFrequency: 90,
            usageHours: 1560,
            testTypes: 'Dissolution testing, Chemical tests',
            operators: 'Lisa Anderson',
            notes: 'Under preventive maintenance. Lamp replacement scheduled.',
            scheduledMaintenance: [
                {
                    start: '2024-12-12T10:00',
                    end: '2024-12-12T15:00',
                    type: 'Preventive Maintenance',
                    technician: 'Robert Wilson',
                    notes: 'Lamp replacement and optical alignment'
                }
            ]
        },
        {
            id: 7,
            code: 'BAL-001',
            name: 'Analytical Balance 1',
            type: 'Analytical Balance',
            manufacturer: 'Mettler Toledo',
            modelNumber: 'XPE205',
            serialNumber: 'SN-BAL-2023-001',
            location: 'QC Lab - Room 101',
            status: 'operational',
            purchaseDate: '2023-01-10',
            warrantyExpiry: '2026-01-10',
            lastCalibration: '2024-12-01',
            nextCalibration: '2025-03-01',
            calibrationFrequency: 90,
            usageHours: 3200,
            testTypes: 'Physical tests, Content uniformity',
            operators: 'John Smith, Sarah Johnson, Emily Davis, Lisa Anderson',
            notes: 'Readability: 0.01mg. Capacity: 220g. Temperature controlled environment.',
            scheduledMaintenance: []
        },
        {
            id: 8,
            code: 'AUTO-001',
            name: 'Autoclave',
            type: 'Sterilization Equipment',
            manufacturer: 'Tuttnauer',
            modelNumber: '3870ELV',
            serialNumber: 'SN-AUTO-2023-001',
            location: 'Microbiology Lab - Room 201',
            status: 'operational',
            purchaseDate: '2023-02-28',
            warrantyExpiry: '2026-02-28',
            lastCalibration: '2024-11-10',
            nextCalibration: '2025-02-10',
            calibrationFrequency: 90,
            usageHours: 1420,
            testTypes: 'Micro tests, Sterilization',
            operators: 'Sarah Johnson, Robert Wilson',
            notes: 'Chamber capacity: 85L. Sterilization cycles at 121°C and 134°C.',
            scheduledMaintenance: [
                {
                    start: '2025-01-20T08:00',
                    end: '2025-01-20T12:00',
                    type: 'Preventive Maintenance',
                    technician: 'Robert Wilson',
                    notes: 'Door seal inspection and gasket replacement if needed'
                }
            ]
        },
        {
            id: 9,
            code: 'FURN-001',
            name: 'Muffle Furnace',
            type: 'Heating Equipment',
            manufacturer: 'Nabertherm',
            modelNumber: 'L 40/11',
            serialNumber: 'SN-FURN-2023-001',
            location: 'QC Lab - Room 104',
            status: 'operational',
            purchaseDate: '2023-03-15',
            warrantyExpiry: '2026-03-15',
            lastCalibration: '2024-10-20',
            nextCalibration: '2025-01-20',
            calibrationFrequency: 90,
            usageHours: 890,
            testTypes: 'Loss on drying, Ash content',
            operators: 'Robert Wilson, Emily Davis',
            notes: 'Max temperature: 1100°C. Chamber volume: 40L.',
            scheduledMaintenance: []
        },
        {
            id: 10,
            code: 'PH-001',
            name: 'pH Meter',
            type: 'pH Measurement',
            manufacturer: 'Mettler Toledo',
            modelNumber: 'SevenCompact S220',
            serialNumber: 'SN-PH-2023-001',
            location: 'QC Lab - Room 101',
            status: 'operational',
            purchaseDate: '2023-01-20',
            warrantyExpiry: '2026-01-20',
            lastCalibration: '2024-12-05',
            nextCalibration: '2025-01-05',
            calibrationFrequency: 30,
            usageHours: 2650,
            testTypes: 'pH determination, Chemical tests',
            operators: 'John Smith, Emily Davis, Lisa Anderson',
            notes: 'Benchtop pH meter with temperature compensation. Monthly calibration required.',
            scheduledMaintenance: []
        },
        {
            id: 11,
            code: 'SPEC-001',
            name: 'FTIR Spectrophotometer',
            type: 'Fourier Transform Infrared Spectroscopy (FTIR)',
            manufacturer: 'Bruker',
            modelNumber: 'Alpha II',
            serialNumber: 'SN-FTIR-2023-001',
            location: 'QC Lab - Room 103',
            status: 'operational',
            purchaseDate: '2023-06-10',
            warrantyExpiry: '2026-06-10',
            lastCalibration: '2024-11-15',
            nextCalibration: '2025-02-15',
            calibrationFrequency: 90,
            usageHours: 720,
            testTypes: 'Identity testing, Structural analysis',
            operators: 'Sarah Johnson, Emily Davis',
            notes: 'ATR sampling module. Range: 4000-400 cm⁻¹.',
            scheduledMaintenance: []
        },
        {
            id: 12,
            code: 'DISS-001',
            name: 'Dissolution Tester',
            type: 'Dissolution Testing',
            manufacturer: 'Agilent Technologies',
            modelNumber: '708-DS',
            serialNumber: 'SN-DISS-2023-001',
            location: 'QC Lab - Room 102',
            status: 'out-of-service',
            purchaseDate: '2023-04-20',
            warrantyExpiry: '2026-04-20',
            lastCalibration: '2024-08-10',
            nextCalibration: '2024-11-10',
            calibrationFrequency: 90,
            usageHours: 1340,
            testTypes: 'Dissolution testing',
            operators: 'Lisa Anderson',
            notes: 'Out of service - motor replacement required. 8-vessel configuration.',
            scheduledMaintenance: [
                {
                    start: '2024-12-15T08:00',
                    end: '2024-12-17T17:00',
                    type: 'Repair',
                    technician: 'External Service',
                    notes: 'Motor replacement and full system calibration'
                }
            ]
        }
    ],
    
    instrumentTypes: [
        'High Performance Liquid Chromatography (HPLC)',
        'Gas Chromatography (GC)',
        'UV-Visible Spectrophotometry',
        'Karl Fischer Titration',
        'Fourier Transform Infrared Spectroscopy (FTIR)',
        'Analytical Balance',
        'pH Measurement',
        'Dissolution Testing',
        'Sterilization Equipment',
        'Heating Equipment',
        'Particle Size Analyzer',
        'Moisture Analyzer',
        'Viscometer',
        'Refractometer'
    ],
    
    locations: [
        'QC Lab - Room 101',
        'QC Lab - Room 102',
        'QC Lab - Room 103',
        'QC Lab - Room 104',
        'Microbiology Lab - Room 201',
        'R&D Lab - Room 301',
        'Production Floor - Area A',
        'Production Floor - Area B',
        'Warehouse - Cold Storage'
    ],
    
    testTypes: [
        'Potency testing',
        'Impurity testing',
        'Content uniformity',
        'Dissolution testing',
        'Stability testing',
        'Residual solvents',
        'Moisture content',
        'Chemical tests',
        'Physical tests',
        'Micro tests',
        'Identity testing',
        'Loss on drying',
        'Ash content',
        'pH determination',
        'Particle size distribution',
        'Structural analysis',
        'Sterilization'
    ],
    
    qualifiedOperators: [
        'John Smith',
        'Sarah Johnson',
        'Michael Chen',
        'Emily Davis',
        'Robert Wilson',
        'Lisa Anderson',
        'David Lee',
        'James Martinez'
    ],
    
    statuses: ['operational', 'maintenance', 'calibration', 'out-of-service']
};